language: node_js
node_js:
  - "10"
branches:
  only:
    - master
    - testnet
install:
  - npm install
script:
  - npm run build-monaco && npm run build-mocha
  - npm run dist
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "ide.acrylplatform.com"
    skip_cleanup: true
    local_dir: dist/
    region: eu-central-1
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "idetestnet.acrylplatform.com"
    skip_cleanup: true
    local_dir: dist/
    region: eu-central-1
    on:
      branch: testnet
